[controller]
address  = "192.168.1.1"
port = 443
username = "automation"
password = ""
site = "default"

[logging.console]
enabled = true
level = "DEBUG"

[logging.file]
enabled = false
level = "INFO"

[logging.email]
enabled = false
level = "WARN"
smtp_server = "email-smtp.us-east-1.amazonaws.com"
smtp_port = 587
smtp_username = ""
smtp_password = ""
sender = ""
recipients = [""]

[isc-acls]
enabled = true
allowed = ["research", "torexit"]

[isc-acls.research]
name = "Dynamic - ISC Research Endpoints"
endpoint = 'threatcategory/research'

[isc-acls.torexit]
name = "Dynamic - ISC TOR Exit Nodes"
endpoint = 'threatlist/torexit'